export enum PebbleForeignFunc {
  GraphicsSetFillColor,
  GraphicsSetStrokeColor,
  GraphicsSetStrokeWidth,
  ControlsWait,
  SensorsAccelerometer,
  SensorsBattery,
  SensorsBatteryState,
  SensorsPhoneConnected,
  TimeWallTime,
  TimeTime24h,
  TimeTime,
  SensorsCurrentWatchModel,
  SensorsCurrentWatchColor,
}